### ISSUE TITLE
Bandwidth plot does not show in Firefox

### ISSUE THREAD

**Issue by pastewka** [ComputationalMechanics/TopoBank#238]
The bandwidth plot is not rendered in Firefox

<img width="462" alt="grafik" src="https://user-images.githubusercontent.com/2530391/60842807-4e94ee80-a1d5-11e9-8297-60b8b86eb6c1.png">

In Chrome it works

<img width="462" alt="grafik" src="https://user-images.githubusercontent.com/2530391/60842904-8f8d0300-a1d5-11e9-8df6-c0c970a6caf7.png">

**Comment by mcrot** [comment]
For #514, we need to plot the bandwidths on a tab which contents are not visible initially. Here the plottable plot is not rendered correctly. I'm replacing now the badwidth plot with a bokeh one, hopefully this here is then solved, too.
