### ISSUE TITLE
Analysis: Overview vs detailed view

### ISSUE THREAD

**Issue by pastewka** [ComputationalMechanics/TopoBank#308]
It is unclear what the „open“ button does.

Decision: There is only chevron. Everything reachable through the chevron is a modal. For the contact mechanics part, we have „modify“ to change parameters, „download“ to download, „contact geometry“ to show contact area and pressure (like the old site).

**Comment by mcrot** [comment]
The main thing the "open" button does is to show only the results for one analysis function.
It is like expanding the results on one function to full screen.

Isn't this still useful, also for other analysis function which don't cannot be modified (yet), e.g. for height distribution?
I'm hesitant to give up this and to show a close-up in a modal only if there is sth. to modify.

**Comment by pastewka** [comment]
Let's keep as is. I agree that it is useful.
