### ISSUE TITLE
Contact Mechanics Download enhancement

### ISSUE THREAD

**Issue by lthimons** [ComputationalMechanics/TopoBank#435]
The contact mechanics download seems to work nicely, but I have a small issue with the files. When opening the .nc files, the user needs to specify the variable to read in. The readme file was helpful in providing the default "pressure" variable, but I found myself guessing for the names of variables such as "gap", since the "pressure" variable is not identical to what the website shows (it lists "contact pressure").

 it might make sense to list in the readme file what the names of the variables are that the user has access to in the .nc files.

**Comment by mcrot** [comment]
In the meanwhile, the names of the variables have been included. Excerpt of readme file:
```
So each line also refers to one NetCDF file in the directory, it corresponds to
one external pressure. Inside the NetCDF file you'll find the variables

* `contact_points`: boolean array, true if point is in contact
* `pressure`: floating-point array containing local pressure (in units of `E*`)
* `gap`: floating-point array containing the local gap
* `displacement`: floating-point array containing the local displacements

as well as the attributes

* `mean_pressure`: mean pressure (in units of `E*`)
* `total_contact_area`: total contact area (fractional)
```
So I'm closing this.
