### ISSUE TITLE
Adjust to new PyCo repository structure

### ISSUE THREAD

**Issue by mcrot** [ComputationalMechanics/TopoBank#475]
PyCo will be divided in 3-4 repositories. 

Links in Terms & Conditions will be adjusted in #490 .

**Comment by mcrot** [comment]
I think #403 , #83 , and #335 all depend on this issue, correct? 
Maybe I should start using the new repositories. Is this ready or should I wait @AntoineSIMTEK  and @pastewka ?

**Comment by pastewka** [comment]
Please wait. It works in serial but not yet in parallel. Since we are currently making further changes to the muFFT backend, I think we should wait with the migration until things on our end have solidified.

**Comment by mcrot** [comment]
This has been implemented.
