### ISSUE TITLE
Feature request: Flag that there is a newer version

### ISSUE THREAD

**Issue by tdbjacobs** [ComputationalMechanics/TopoBank#513]
If a person is looking at a topography that has a newer version, I would have a little notification somewhere (maybe a badge on the "Version Number" box) that let's them know that a newer version is available

**Comment by mcrot** [comment]
Now I've implemented this:
![grafik](https://user-images.githubusercontent.com/9113541/92930387-4c19ce80-f442-11ea-875d-d84c843f9506.png)

If there are published versions, now also "Work in progress" has a badge:
![grafik](https://user-images.githubusercontent.com/9113541/92930485-6ce22400-f442-11ea-90df-a4cf7e46272b.png)

The newest published version has no such badge:
![grafik](https://user-images.githubusercontent.com/9113541/92930553-82574e00-f442-11ea-918f-ae8083b140a5.png)

I'm closing this now. If this is not what you want, please reopen.
