### ISSUE TITLE
Bandwidth plot uglier for many topographies

### ISSUE THREAD

**Issue by mcrot** [ComputationalMechanics/TopoBank#535]
Now, after switching from plottable to bokeh for the bandwidth plots, they do not look nice because of the 
labels:
![grafik](https://user-images.githubusercontent.com/9113541/97874673-a1bf7880-1d19-11eb-9bdb-3e96bda33c81.png)

Also you cannot click on every topography any more.

**Comment by mcrot** [comment]
Update from @tdbjacobs and @pastewka :

>   * The bandwidth plot on a surface with a lot of topographies is a
>     mess. I can't read the text. (See /Screenshot1.png/, attached)
> 
> I agree. We updated this to use the Bokeh framework in this release but 
> I think the old bandwidth plot was much better.
> 
> @Michael: Can you roll back that change?
Not that easy. The problem with the old "plottable" solution was that it did not load in the hidden tab. That was the main reason for me to do the transition to "bokeh" when implementing the gallery as initial tab.

I can try to leave out the labels at some point.

**Comment by mcrot** [comment]
I think I'll release this first before implementing #239, because of other bugs. Let's see how it looks like
with big surfaces in production, it can't be uglier than this. Reopen if it still needs improvements.

**Comment by pastewka** [comment]
Sounds good!
