### ISSUE TITLE
"Parent Surface" instead of "Surface" in Topography Properties

### ISSUE THREAD

**Issue by mcrot** [ComputationalMechanics/TopoBank#541]
>   * In Surface > Properties > Properties, two comments:
> 
>      1. Instead of just saying "Surface", this should say something like
>         "Parent surface" or "Surface imaged" or something else. I fear
>         that if it just says "Surface", people may misunderstand the
>         meaning of "surface" and may think that this is the name of this
>         particular topography. 
> 
> Okay. Will need to look at the interface to see what you are saying.
I think you mean "Surface > Topography > Properties"?
I understand, I would just write "Parent surface", this helps to understand the hierarchy of Surfaces and Topographies.

Or we can just leave it out, since we now have the tabs - there is already a link to the surface.

**Comment by pastewka** [comment]
We are talking about this, correct?

![image](https://user-images.githubusercontent.com/2530391/98565028-65f25900-22ad-11eb-859c-fc20ed134951.png)

I would just remove the "Surface" line because it should be clear from the tabs which surface this topography belongs to.

**Comment by mcrot** [comment]
Yes, okay, I simply remove it.
