### ISSUE TITLE
Tab for sharing should give the option to share everything in the workspace

### ISSUE THREAD

**Issue by mcrot** [ComputationalMechanics/TopoBank#554]
In the new layout (see #304) the tab "share" should give the option to share everything in the workspace with a user.

_Originally posted by @pastewka in https://github.com/ComputationalMechanics/TopoBank/issues/300#issuecomment-512874535_

**Comment by pastewka** [comment]
I no longer understand what I meant by "sharing everything in the workspace". Everything in the "basket", i.e. everything that has been selected?

**Comment by mcrot** [comment]
Yes, everything which is currently selected. I think we called the "basket" also "workspace" when we developed the idea.

We should be careful here  - if only one topography is selected, we cannot share only that topography. We share full surfaces with *all* their topographies so far.

**Comment by pastewka** [comment]
That's right. I'm unsure whether this is a good idea and would postpone it...

**Comment by pastewka** [comment]
(Or close this issue.)

**Comment by mcrot** [comment]
Okay, closing it.
