### ISSUE TITLE
Significant digits for RMS values

### ISSUE THREAD

**Issue by tdbjacobs** [ComputationalMechanics/TopoBank#557]
It seems silly to show a dozen or more significant digits for RMS parameters. 

Perhaps we could limit it to some smaller number ---- 5?

**Comment by mcrot** [comment]
Yes, I would like to discuss this together with @pastewka . This is also related to #492.

**Comment by pastewka** [comment]
Okay, let's limit this to 5. We should still have the exact number somewhere (in a download?) In case someone wants to reimplement our algorithm.

**Comment by mcrot** [comment]
I'm going to reduce to 5 significant digits on the page and in the download we'll keep all digits.

**Comment by pastewka** [comment]
Sounds good!
