### ISSUE TITLE
Varying results for RMS Slope

### ISSUE THREAD

**Issue by mcrot** [ComputationalMechanics/TopoBank#561]
Following issue was sent to us by mail:

> Hey Micheal,
> 
> About the online program contact.engineering, we meet another issue about analysis.
> 
> For root mean square slope computation (RMS slope), we find there is significant discrepancy between the results from the online program and the results from our own calculation. I shared an example with you (sample1_5000_FIXEDv2p1.asc) in Ceramic trial 2 by me ([name]) for better demonstration.
> 
> Our algorithm is shown as follows. Before analysis (Matlab), the profiles are either normalized by deducting the mean value (h=h-mean(h)) or deducting the linear fitted reference line (h=ax+b). It does not matter because the results from both ones have little difference. RMS slope is computed by the following equation.
> ![grafik](https://user-images.githubusercontent.com/9113541/100319336-b660fa80-2fbf-11eb-8a5d-4ac6344c6e4c.png)
>  where x, h are coordinates of discrete points, N is total number of points, and L is the length of the profile. Except for these procedures, we did not do more.
> We find that the computed RMS slope is 1.1974 by our own algorithm. However, the output RMS slope from contact.engineering is 1.6223. Attached screenshot also illustrates this comparison. In addition, we repeated all computations for all my samples. I find RMS slope calculated from contact.engineering is always greater ~30% than RMS slope calculated from our own algorithm.
> 
> We are figuring out the reason for this discrepancy. We expect that the big discrepancy is attributed to different algorithms for discrete data point computations. However, we have no way to know the algorithm for contact.engineering. I am wondering whether you can provide some information about the algorithm for RMS slope computation. Or, if you have better idea about that, I appreciate it. Finding out the behind reason is very important for my current work.
> 
> Thanks,
>  [...]

Attachment:
![grafik](https://user-images.githubusercontent.com/9113541/100319442-e5776c00-2fbf-11eb-8bc4-26ec3c4093b4.png)

**Comment by mcrot** [comment]
Hm - at a first glance it seems that the algorithms are different. The code for RMS slope can be found here:

https://github.com/ComputationalMechanics/SurfaceTopography/blob/b03e71f102f9a09a8211289bf6ddc3c73f249778/SurfaceTopography/Uniform/ScalarParameters.py#L76

for `topography.dim == 1`. The derivative is calculated here: https://github.com/ComputationalMechanics/SurfaceTopography/blob/b03e71f102f9a09a8211289bf6ddc3c73f249778/SurfaceTopography/Uniform/common.py#L51

@pastewka or @AntoineSIMTEK , can you help here?

**Comment by pastewka** [comment]
The algorithm that is used is the one for nonuniform line scans. The documentation is here:

https://computationalmechanics.github.io/SurfaceTopography/source/SurfaceTopography.Nonuniform.html#SurfaceTopography.Nonuniform.ScalarParameters.rms_slope

**Comment by pastewka** [comment]
TopoBank uses a different expression that in my opinion is better than the above. In the limit of small \Delta x they should be the same. I think what is happening is that the very steep regions in above line scan dominate h_rms' and that therefor it matters how it is computed.

**Comment by pastewka** [comment]
Our algorithm is correct, I am closing this.
