### ISSUE TITLE
License of published surfaces is never shown in the web interface

### ISSUE THREAD

**Issue by pastewka** [ComputationalMechanics/TopoBank#566]
The license of a published surface is listed in the downloaded data file but not on the web interface. Do we need to show it somewhere?

Any opinions @mcrot and @tdbjacobs ?

**Comment by tdbjacobs** [comment]
Seems like it would be useful to show. Just so people know up front how
they can reuse a surface.
-Tevis

Tevis Jacobs
William Kepler Whiteford Faculty Fellow and Associate Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
tjacobs@pitt.edu

**Comment by mcrot** [comment]
Yes, I fully agree, I simply forgot this. That's easy to fix and will be included in the next release.

**Comment by mcrot** [comment]
I've implemented this and it looks like this:
![grafik](https://user-images.githubusercontent.com/9113541/101155199-117d9780-3627-11eb-943b-4baec82b60c6.png)

Let me know if you need sth. else here. I would prefer not to explain the license myself but only refer to the description on the creative commons page, which is easy to read, I think.
