### ISSUE TITLE
About highest frequency or wavelength of PSD curves

### ISSUE THREAD

**Issue by Rick224339** [ComputationalMechanics/TopoBank#568]
Usually, the highest frequency of a PSD curve follows N=2BL, where N is the total number of points, B is the bandwidth (highest frequency of one-side PSD curve), and L is the total length. In other words, according to this simple criterion, the maximum frequency in one-side PSD should be B = N/2L or half of the number density per length unit N/L.. In addition, the total number of the line profile N is the same as the final output number of PSD curve points, namely N(profile) = N(PSD curve points).

One of my line profiles has only 10 nm between two adjacent points. However, minmum wavelength or maximum frequency of the PSD curve computed from contact.engineering is about 0.1 nm. This is far beyond the resolution of my profile. In addition, the number of data points of my profile is just 300 or so, but the number of output PSD curve data point is over 4000. I see the algorithm. It seems there is a data extrapolation between adjacent points.

I did not understand the behind logics for this. Could anyone give an explantion in detail?

**Comment by Rick224339** [comment]
Fix: In addition, the total number of the line profile N is the same as the final output number of PSD curve points, namely N(profile) = N(PSD curve points) for double-side PSD or 0.5N(profile) = N(PSD curve points) for one-side PSD.

**Comment by Rick224339** [comment]
Re: AntoineSIMTEK

I plot 1D PSD of a single line profile and each datafile contains only one lineprofile.

For the second question, probably, I have a wrong understanding. It is more like my guess. 

Thanks for your comment. If I understand correctly, this is due to the fact that the PSD online algrithm evaluates 2D radially averaged PSD curves based on the 1D line profile. Right? However, how to understand that maximum PSD frequency computed online is greater than my method based on the criterion mentioned in the question?

**Comment by AntoineSIMTEK** [comment]
Ok then the function used to compute the PSD is powerspectrum_1D

It is computed by this function if the points are spaced uniformly:

https://github.com/ComputationalMechanics/SurfaceTopography/blob/378e7024fedec42ba610eb45ee7f14749d258202/SurfaceTopography/Uniform/PowerSpectrum.py#L39-L103

this returns a PSD on N/2 points spaced q vectors spaced by 2 pi / L , with L the physical size of your scan
so the highest wavector is pi N / L. 

For nonuniformly spaced grid points it uses (with default arguments): 

https://github.com/ComputationalMechanics/SurfaceTopography/blob/378e7024fedec42ba610eb45ee7f14749d258202/SurfaceTopography/Nonuniform/PowerSpectrum.py#L98-L173

In the nonuniform case it would be possible to have 4000 points in the PSD indead.

If your topography is considered as uniform then I don't understand what is going on.

**Comment by Rick224339** [comment]
My line profile has nonuniform data distribution. It seems that nonuniform case will output more data points in PSD curves and bigger maximum frequency. What is the behind reason for that?

**Comment by AntoineSIMTEK** [comment]
There are two reasons: the maximum frequency present in your data is given by the smallest grid spacing. 

Also, linear interpolation usually decreases the amplitude of the data if the grid spacing is too big.

![Uploading IMG_20201212_071842.jpg…]()

**Comment by Rick224339** [comment]
Make sense. Thank you.

**Comment by AntoineSIMTEK** [comment]
You are welcome. I am closing this issue now.

**Comment by AntoineSIMTEK** [comment]
We discussed this in todays teleconference. 

Using a spacing that is five times less then the smallest spacing produces a PSD that potentially reaches far beyond the actual resolution of the measurement. It is very likely to produce a q^-4 scaling regime that is not real. 

We need to think about until which wavevector the PSD should be considered as reliable. The q^-4 scaling is not necessary a good indicator since it can be due to true facetting or kinks of the surface.

**Comment by Rick224339** [comment]
Thanks for this information. For q^-4 scaling, it appears usually in profiles by stylus profilometry and AFM due to the curvature of probe tip. For examples, if the probe goes through an infinitely sharp spike, the probe cannot resolve the shape of the spike but instead the inverse profile of the curved probe itself. Any high frequency component in PSD attributed to features approximately smaller than the probe tip size is regarded as artifact which mathematically appears q^-4 scaling in PSD for this reason. However, in this case, q^-4 scaling in PSD is due to artificially extrapolating data between two adjacent points or the resolution limit in profile. I did not quite understand this mechanism.

**Comment by AntoineSIMTEK** [comment]
E.L. Church, P.Z. Takacs, Effects of the nonvanishing tip size in mechanical profile measurements, in: C.P. Grover (Ed.), Opt. Test. Metrol. III Recent Adv. Ind. Opt. Insp., 1991: pp. 504–514. https://doi.org/10.1117/12.51099

In the tip artifact, the q^-4 scaling is actually due to the kinks between the spherical cusps created by the tip convolution.

**Comment by pastewka** [comment]
I just release SurfaceTopography 0.92.0 - if you just update the dependency to this release, this fixes this issue without further modification of TopoBank @mcrot

**Comment by mcrot** [comment]
Okay, thanks!
